var note_to_midi_mapper = function(note) {
  switch (note) {
    case 'c1':
      return 0;
    case 'db':
      return 1;
    case 'd':
      return 2;
    case 'eb':
      return 3;
    case 'e':
      return 4;
    case 'f':
      return 5;
    case 'gb':
      return 6;
    case 'g':
      return 7;
    case 'ab':
      return 8;
    case 'a':
      return 9;
    case 'bb':
      return 10;
    case 'b':
      return 11;
    case 'c4':
      return 36;
    case 'db':
      return 37;
    case 'd':
      return 38;
    case 'eb':
      return 39;
    case 'e':
      return 40;
    case 'f':
      return 41;
    case 'gb':
      return 42;
    case 'g':
      return 43;
    case 'ab':
      return 44;
    case 'a':
      return 45;
    case 'bb':
      return 46;
    case 'b':
      return 47;
    case 'c7':
      return 72;
    case 'db':
      return 73;
    case 'd':
      return 74;
    case 'eb':
      return 75;
    case 'e':
      return 76;
    case 'f':
      return 77;
    case 'gb':
      return 78;
    case 'g':
      return 79;
    case 'ab':
      return 80;
    case 'a':
      return 81;
    case 'bb':
      return 82;
    case 'b':
      return 83;
    case 'c10':
      return 108;
    case 'db':
      return 109;
    case 'd':
      return 110;
    case 'eb':
      return 111;
    case 'e':
      return 112;
    case 'f':
      return 113;
    case 'gb':
      return 114;
    case 'g':
      return 115;
    case 'ab':
      return 116;
    case 'a':
      return 117;
    case 'bb':
      return 118;
    case 'b':
      return 119;
  }
};
